#!/usr/bin/env bash
# build-pake-apps.sh — package web apps as native windows via pake-cli + PKGBUILD.
#
# For each entry in APPS, this generates a per-app PKGBUILD under
#   ~/.cache/pake-build/<name>-app/
# runs pake-cli inside it to produce a .deb, repackages the .deb's contents
# into a pacman-installable Arch package, and installs it via makepkg -si.
#
# Result: a /usr/bin/<name>-app binary and a .desktop file managed by pacman.
# Keybinds in hypr/niri call the binary directly (e.g. `gemini-app`).
#
# Usage:
#   ./build-pake-apps.sh                # build any apps not yet installed
#   ./build-pake-apps.sh <name>         # build a single app (e.g. gemini)
#   ./build-pake-apps.sh --list         # show declared apps
#   ./build-pake-apps.sh --force        # rebuild all (passes -f to makepkg)
#
# Build deps (provided by makedepends in the PKGBUILD): nodejs, npm, rust,
# binutils. First-run setup also wants `base-devel`. Each PKGBUILD installs
# pake-cli locally inside its own $srcdir, so no global node_modules.
#
# Heads up: pake builds via Tauri/Rust. Expect ~5–10 minutes per app the
# first time (subsequent rebuilds reuse cargo's local cache). Plan accordingly.

set -euo pipefail

# ---------------------------------------------------------------------------
# Apps. Add new entries here. Format: name|url|title
# Binary lands at /usr/bin/<name>-app; pkgname is <name>-app.
# ---------------------------------------------------------------------------
APPS=(
  "gemini|https://gemini.google.com|Gemini"
  "chatgpt|https://chatgpt.com|ChatGPT"
  "claude|https://claude.ai|Claude"
  "gcal|https://calendar.google.com|Google Calendar"
  "gmail|https://mail.google.com|Gmail"
  "gkeep|https://keep.google.com|Google Keep"
  "ha|https://k47hlod95qzgumfbtnp8n8r610oh2mbo.ui.nabu.casa/|Home Assistant"
  "x|https://x.com|X"
)

BUILD_ROOT="${XDG_CACHE_HOME:-$HOME/.cache}/pake-build"

# ---------------------------------------------------------------------------
# PKGBUILD template. Placeholders: {NAME}, {URL}, {TITLE}.
# package() extracts the .deb pake produces (Tauri's deb bundler) into
# $pkgdir; pacman then owns /usr/bin/<name>-app and the .desktop file.
# ---------------------------------------------------------------------------
read -r -d '' PKGBUILD_TEMPLATE <<'PKGBUILD_EOF' || true
# Generated by build-pake-apps.sh — regenerated on every build.
pkgname={NAME}-app
pkgver=1.0.0
pkgrel=1
pkgdesc="{TITLE} as a native Wayland window (built via Pake)"
arch=("x86_64")
url="https://github.com/tw93/Pake"
license=("MIT")
depends=("webkit2gtk-4.1" "gtk3" "libayatana-appindicator")
makedepends=("nodejs" "npm" "rust" "binutils")
options=(!strip !debug)

_app_url="{URL}"
_app_name="{NAME}-app"
_app_title="{TITLE}"

build() {
  cd "$srcdir"
  if [[ ! -x ./node_modules/.bin/pake ]]; then
    npm install --prefix "$srcdir" pake-cli
  fi
  PATH="$srcdir/node_modules/.bin:$PATH" \
    pake "$_app_url" --name "$_app_name" --title "$_app_title"
}

package() {
  cd "$srcdir"
  local deb
  deb=$(find . -maxdepth 6 -type f -name '*.deb' | head -n1)
  if [[ -z "$deb" ]]; then
    msg "no .deb produced by pake under $srcdir"
    return 1
  fi
  msg "extracting $deb"
  bsdtar -xf "$deb" -C "$pkgdir" ./usr 2>/dev/null || {
    bsdtar -xf "$deb"
    bsdtar -xf data.tar.* -C "$pkgdir"
  }
}
PKGBUILD_EOF

# ---------------------------------------------------------------------------
list_apps() {
  printf '%-10s %-44s %s\n' "NAME" "URL" "TITLE"
  for entry in "${APPS[@]}"; do
    IFS='|' read -r n u t <<<"$entry"
    printf '%-10s %-44s %s\n' "$n" "$u" "$t"
  done
}

is_installed() { pacman -Q "$1" &>/dev/null; }

build_one() {
  local name="$1" url="$2" title="$3"
  local pkg="${name}-app"
  local dir="${BUILD_ROOT}/${pkg}"

  if is_installed "$pkg" && [[ "${FORCE:-0}" != "1" ]]; then
    echo "skip $pkg (installed; pass --force to rebuild)"
    return 0
  fi

  mkdir -p "$dir"
  local pkgbuild="${PKGBUILD_TEMPLATE//\{NAME\}/$name}"
  pkgbuild="${pkgbuild//\{URL\}/$url}"
  pkgbuild="${pkgbuild//\{TITLE\}/$title}"
  printf '%s\n' "$pkgbuild" > "${dir}/PKGBUILD"

  echo "==> building $pkg in $dir"
  ( cd "$dir" && makepkg -si ${FORCE:+-f} )
}

# ---------------------------------------------------------------------------
FORCE=0
SELECTED=""
for arg in "$@"; do
  case "$arg" in
    --list)  list_apps; exit 0 ;;
    --force) FORCE=1 ;;
    -h|--help)
      sed -n '2,/^set -euo/p' "$0" | sed 's/^# \{0,1\}//; /^set -euo/d'
      exit 0
      ;;
    *) SELECTED="$arg" ;;
  esac
done

command -v makepkg >/dev/null \
  || { echo "makepkg not found — install base-devel"; exit 1; }

for entry in "${APPS[@]}"; do
  IFS='|' read -r n u t <<<"$entry"
  if [[ -n "$SELECTED" && "$SELECTED" != "$n" ]]; then continue; fi
  build_one "$n" "$u" "$t"
done

echo
echo "Installed pake apps:"
for entry in "${APPS[@]}"; do
  IFS='|' read -r n _ _ <<<"$entry"
  pacman -Q "${n}-app" 2>/dev/null || true
done
