#!/usr/bin/env bash
# build-pake-apps.sh — package web apps as native windows via pake-cli + PKGBUILD.
#
# For each entry in APPS, this generates a per-app PKGBUILD under
#   ~/.cache/pake-build/<name>-app/
# runs pake-cli inside it to produce a .deb, repackages the .deb's contents
# into a pacman-installable Arch package, and installs it via makepkg -si.
#
# Result: a /usr/bin/<name>-app binary and a .desktop file managed by pacman.
# Keybinds in hypr/niri call the binary directly (e.g. `gemini-app`).
#
# Usage:
#   ./build-pake-apps.sh                # build any apps not yet installed
#   ./build-pake-apps.sh <name>         # build a single app (e.g. gemini)
#   ./build-pake-apps.sh --list         # show declared apps
#   ./build-pake-apps.sh --force        # rebuild all (passes -f to makepkg)
#
# Build deps (provided by makedepends in the PKGBUILD): nodejs, npm, rust,
# binutils. First-run setup also wants `base-devel`. Each PKGBUILD installs
# pake-cli locally inside its own $srcdir, so no global node_modules.
#
# Heads up: pake builds via Tauri/Rust. Expect ~5–10 minutes per app the
# first time (subsequent rebuilds reuse cargo's local cache). Plan accordingly.

set -euo pipefail

# ---------------------------------------------------------------------------
# Apps. Add new entries here. Format: name|url|title|icon_url
# Binary lands at /usr/bin/<name>-app; pkgname is <name>-app.
# icon_url is optional — if set, pake downloads it and uses it as the app
# icon (handles svg/png/ico). If omitted, pake falls back to its own
# heuristics (logo.dev, brandfetch, clearbit, favicon, …) which often
# yields the wrong logo (e.g. plain Google "G" for any *.google.com app).
# ---------------------------------------------------------------------------
APPS=(
  "gemini|https://gemini.google.com|Gemini|https://upload.wikimedia.org/wikipedia/commons/8/8a/Google_Gemini_logo.svg"
  "chatgpt|https://chatgpt.com|ChatGPT|https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg"
  "claude|https://claude.ai|Claude|https://claude.ai/images/claude-app-icon.png"
  "gcal|https://calendar.google.com|Google Calendar|https://upload.wikimedia.org/wikipedia/commons/a/a5/Google_Calendar_icon_%282020%29.svg"
  "gmail|https://mail.google.com|Gmail|https://upload.wikimedia.org/wikipedia/commons/7/7e/Gmail_icon_%282020%29.svg"
  "gkeep|https://keep.google.com|Google Keep|https://cdn.simpleicons.org/googlekeep"
  "ha|https://k47hlod95qzgumfbtnp8n8r610oh2mbo.ui.nabu.casa/|Home Assistant|https://brands.home-assistant.io/homeassistant/icon.png"
  "x|https://x.com|X|https://x.com/apple-touch-icon.png"
)

BUILD_ROOT="${XDG_CACHE_HOME:-$HOME/.cache}/pake-build"

# ---------------------------------------------------------------------------
# PKGBUILD template. Placeholders: {NAME}, {URL}, {TITLE}, {ICON}.
# package() extracts the .deb pake produces (Tauri's deb bundler) into
# $pkgdir; pacman then owns /usr/bin/<name>-app and the .desktop file.
# ---------------------------------------------------------------------------
read -r -d '' PKGBUILD_TEMPLATE <<'PKGBUILD_EOF' || true
# Generated by build-pake-apps.sh — regenerated on every build.
pkgname={NAME}-app
pkgver=1.0.0
pkgrel=1
pkgdesc="{TITLE} as a native Wayland window (built via Pake)"
arch=("x86_64")
url="https://github.com/tw93/Pake"
license=("MIT")
depends=("webkit2gtk-4.1" "gtk3" "libayatana-appindicator")
makedepends=("nodejs" "npm" "rust" "binutils" "imagemagick")
options=(!strip !debug)

_app_url="{URL}"
_app_name="{NAME}-app"
_app_title="{TITLE}"
_app_icon="{ICON}"

build() {
  cd "$srcdir"
  if [[ ! -x ./node_modules/.bin/pake ]]; then
    npm install --prefix "$srcdir" pake-cli
  fi

  # Pake's --hide-title-bar flag is Mac-only and on Linux Tauri's title bar
  # comes from two layers, both of which need to be silenced:
  #
  # (1) Tauri's WebviewWindowBuilder defaults to decorations=true → patch
  #     pake's window.rs to call .decorations(false) on the builder.
  local window_rs="$srcdir/node_modules/pake-cli/src-tauri/src/app/window.rs"
  if [[ -f "$window_rs" ]] && ! grep -q '\.decorations(false)' "$window_rs"; then
    sed -i 's|window_builder\.build()|window_builder.decorations(false).build()|' "$window_rs"
  fi

  # (2) tao (Tauri's windowing backend) unconditionally attaches a custom
  #     GTK HeaderBar on Wayland (close/min/max buttons) regardless of the
  #     builder's `decorations` flag. Pre-fetch deps and patch tao's
  #     window.rs to honor `attributes.decorations` before adding the header.
  #     Cargo treats registry source as immutable (fingerprint based on
  #     .crate hash, not file mtimes), so when we patch we also invalidate
  #     tao's compiled artifacts in this project's target dir to force a
  #     rebuild — otherwise cargo silently uses the stale .o.
  ( cd "$srcdir/node_modules/pake-cli/src-tauri" && cargo fetch >/dev/null 2>&1 ) || true
  local tao_patched=0
  for tao_win in "$HOME"/.cargo/registry/src/*/tao-0.34.*/src/platform_impl/linux/window.rs; do
    [[ -f "$tao_win" ]] || continue
    if ! grep -q "is_wayland && attributes.decorations" "$tao_win"; then
      sed -i 's|^    if is_wayland {$|    if is_wayland \&\& attributes.decorations {|' "$tao_win"
      tao_patched=1
    fi
  done
  if (( tao_patched )); then
    local target_dir="$srcdir/node_modules/pake-cli/src-tauri/target/release"
    if [[ -d "$target_dir" ]]; then
      rm -rf "$target_dir"/.fingerprint/tao-* 2>/dev/null || true
      find "$target_dir/deps" -maxdepth 1 \( -name 'tao-*' -o -name 'libtao-*' \) -delete 2>/dev/null || true
    fi
  fi

  # Rust 1.95 made rust-lld the default linker on x86_64-linux, but it fails
  # to resolve ring 0.17.14's P256 asm symbols ("undefined symbol:
  # ring_core_0_17_14__p256_point_mul" etc.). Force mold for the link step.
  # --targets deb: skip the appimage bundle (its strip step is broken on
  # modern glibc / Arch). package() repackages the .deb into a pacman pkg.
  local -a icon_arg=()
  [[ -n "$_app_icon" ]] && icon_arg=(--icon "$_app_icon")
  PATH="$srcdir/node_modules/.bin:$PATH" \
  RUSTFLAGS="${RUSTFLAGS:-} -C link-arg=-fuse-ld=mold" \
    pake "$_app_url" --name "$_app_name" --title "$_app_title" --targets deb "${icon_arg[@]}"
}

package() {
  cd "$srcdir"
  local deb
  deb=$(find . -maxdepth 6 -type f -name '*.deb' | head -n1)
  if [[ -z "$deb" ]]; then
    msg "no .deb produced by pake under $srcdir"
    return 1
  fi
  msg "extracting $deb"
  bsdtar -xf "$deb" -C "$pkgdir" ./usr 2>/dev/null || {
    bsdtar -xf "$deb"
    bsdtar -xf data.tar.* -C "$pkgdir"
  }

  # pake hardcodes a "pake-" prefix on the binary; symlink so keybinds can
  # call the app by its short name.
  if [[ -x "$pkgdir/usr/bin/pake-${_app_name}" && ! -e "$pkgdir/usr/bin/${_app_name}" ]]; then
    ln -s "pake-${_app_name}" "$pkgdir/usr/bin/${_app_name}"
  fi

  # pake ships two .desktop entries per app; the "com.pake.*" one references
  # an icon outside the search path and shows up as a duplicate launcher entry.
  rm -f "$pkgdir/usr/share/applications/com.pake.${_app_name}.desktop"

  # Rewrite the surviving .desktop file: pake's defaults are noisy
  # ("Name=<binary>", "Comment=Turn any webpage into a desktop app with Rust",
  # empty Categories). Replace with the human-readable title + sane category
  # so launchers and bar widgets show useful labels.
  local desktop="$pkgdir/usr/share/applications/${_app_name}.desktop"
  if [[ -f "$desktop" ]]; then
    sed -i \
      -e "s|^Name=.*|Name=${_app_title}|" \
      -e "s|^Comment=.*|Comment=${_app_title}|" \
      -e "s|^Categories=.*|Categories=Network;WebBrowser;Utility;|" \
      "$desktop"
  fi

  # pake only ships the icon at 512x512. Many Qt/QML launchers (noctalia,
  # plasma) refuse to downscale that far and show a missing-image placeholder
  # (black-and-pink checkerboard). Generate the standard icon-theme sizes
  # from the 512 source via ImageMagick, and drop a copy into pixmaps as a
  # legacy fallback for tools that bypass the icon-theme cache entirely.
  local icon512="$pkgdir/usr/share/icons/hicolor/512x512/apps/pake-${_app_name}.png"
  if [[ -f "$icon512" ]]; then
    local size
    for size in 48 64 128 256; do
      local sized_dir="$pkgdir/usr/share/icons/hicolor/${size}x${size}/apps"
      mkdir -p "$sized_dir"
      magick "$icon512" -resize "${size}x${size}" "$sized_dir/pake-${_app_name}.png"
    done
    mkdir -p "$pkgdir/usr/share/pixmaps"
    cp "$icon512" "$pkgdir/usr/share/pixmaps/pake-${_app_name}.png"
  fi
}
PKGBUILD_EOF

# ---------------------------------------------------------------------------
list_apps() {
  printf '%-10s %-44s %-18s %s\n' "NAME" "URL" "TITLE" "ICON"
  for entry in "${APPS[@]}"; do
    IFS='|' read -r n u t i <<<"$entry"
    printf '%-10s %-44s %-18s %s\n' "$n" "$u" "$t" "${i:-(auto)}"
  done
}

is_installed() { pacman -Q "$1" &>/dev/null; }

build_one() {
  local name="$1" url="$2" title="$3" icon="${4:-}"
  local pkg="${name}-app"
  local dir="${BUILD_ROOT}/${pkg}"

  if is_installed "$pkg" && [[ "${FORCE:-0}" != "1" ]]; then
    echo "skip $pkg (installed; pass --force to rebuild)"
    return 0
  fi

  mkdir -p "$dir"
  local pkgbuild="${PKGBUILD_TEMPLATE//\{NAME\}/$name}"
  pkgbuild="${pkgbuild//\{URL\}/$url}"
  pkgbuild="${pkgbuild//\{TITLE\}/$title}"
  pkgbuild="${pkgbuild//\{ICON\}/$icon}"
  printf '%s\n' "$pkgbuild" > "${dir}/PKGBUILD"

  echo "==> building $pkg in $dir"
  ( cd "$dir" && makepkg -si ${FORCE:+-f} )
}

# ---------------------------------------------------------------------------
FORCE=0
SELECTED=""
for arg in "$@"; do
  case "$arg" in
    --list)  list_apps; exit 0 ;;
    --force) FORCE=1 ;;
    -h|--help)
      sed -n '2,/^set -euo/p' "$0" | sed 's/^# \{0,1\}//; /^set -euo/d'
      exit 0
      ;;
    *) SELECTED="$arg" ;;
  esac
done

command -v makepkg >/dev/null \
  || { echo "makepkg not found — install base-devel"; exit 1; }

for entry in "${APPS[@]}"; do
  IFS='|' read -r n u t i <<<"$entry"
  if [[ -n "$SELECTED" && "$SELECTED" != "$n" ]]; then continue; fi
  build_one "$n" "$u" "$t" "$i"
done

echo
echo "Installed pake apps:"
for entry in "${APPS[@]}"; do
  IFS='|' read -r n _ _ _ <<<"$entry"
  pacman -Q "${n}-app" 2>/dev/null || true
done
